[package]
name = "reqwest-cache"
version = "0.1.0"
authors = ["Alexander Polyakov <aleksandr.polyakov@kupibilet.ru>"]

[dependencies]
reqwest = "0.8.1"
lru_time_cache = "0.7"
serde = "1.0"

[dev-dependencies]
serde_json = "1.0"
serde_derive = "1.0"
